Dev 41 create comments section
devneu/frontend pull request #23
Opened 2021-08-03 14:55 UTC by olehrdk

## Ticket
Link to ticket: https://bsalo.atlassian.net/jira/software/projects/DEV/boards/2/backlog?selectedIssue=DEV-41

## Description
*Please provide a small summary of your changes and how they resolved the issues in the ticket:*

- Comments Component added
- Tests for Comments component added
- BlogPost page added

## Screenshots

![image](https://user-images.githubusercontent.com/59115718/128037461-5bc9ec36-da2c-4516-baca-f0cf8bd5f0ce.png)

## Checklist

- [x] Did you test it?
- [x] Did you add tests?
- [x] Did you add to the storybook?

2021-08-11 08:23 UTC, dev1B requested changes

2021-08-11 08:23 UTC, dev1B commented on src/actions/BlogActions.tsx
> +  static addComment = (payload: { value: string; postId: number; parentId: number | null }) => ({
if u adding new comment u will not have postId

2021-08-11 08:23 UTC, dev1B commented on src/actions/BlogActions.tsx
> +  COMMENT_ADDED = '[Blog]: Comment Added',
ADD_COMMENT

2021-08-11 08:23 UTC, dev1B commented on src/actions/BlogActions.tsx
> +  COMMENT_ADDED = '[Blog]: Comment Added',
Add Comment

2021-08-11 09:55 UTC, olehrdk commented on src/actions/BlogActions.tsx
> +  static addComment = (payload: { value: string; postId: number; parentId: number | null }) => ({
postId needed only to find post where we have to add comment

2021-08-12 08:09 UTC, dev1B requested changes

2021-08-12 08:09 UTC, dev1B commented on src/components/Comments/Comments.test.tsx
> +      .create(<Comments commentsList={commentsList} onCommentAdded={() => console.log('added')} />)
jest.fn

2021-08-12 08:09 UTC, dev1B commented on src/components/AddCommentForm/AddCommentForm.tsx
> +  const [textAreaValue, setTextAreaValue] = useState('');
use form hooks please

2021-08-12 18:59 UTC, Skitus commented on src/components/AddCommentForm/AddCommentForm.tsx
> +               onChange={(e) => { setTextAreaValue(e.target.value) }}
Use react-hook-form. Don`t develop your logic(u don`t need to hang listener)

2021-08-12 19:05 UTC, Skitus commented on src/components/AddCommentForm/AddCommentForm.tsx
> +               disabled={disabled}
use react-hook form. Why u use this button disabled ? Add some logic. For instance add your comment to console

2021-08-12 19:19 UTC, Skitus commented on src/pages/BlogPost/BlogPostContainer.tsx
> +export default connect<StateProps, DispatchProps, OwnProps, InitialState>(mapStateToProps, mapDispatchToProps)(BlogPost);
Are we have to use Class components ?

2021-08-12 19:22 UTC, Skitus commented on src/reducers/blog.tsx
> +            commentId: comments.length + 1,
Mb better use comments.length++

2021-08-12 19:22 UTC, Skitus commented on src/reducers/blog.tsx
> +            userName: `Anonim ${comments.length + 1}`,
Mb better use comments.length++ or ++comments.length

2021-08-13 06:40 UTC, olehrdk commented on src/components/AddCommentForm/AddCommentForm.tsx
> +               disabled={disabled}
Button disabled when textarea value length = 0
Console.log throws an eslint error
Which logic I have to add?

2021-08-13 06:42 UTC, olehrdk commented on src/pages/BlogPost/BlogPostContainer.tsx
> +export default connect<StateProps, DispatchProps, OwnProps, InitialState>(mapStateToProps, mapDispatchToProps)(BlogPost);
There aren't any Class Components

2021-08-13 09:52 UTC, dev1B requested changes

2021-08-13 09:52 UTC, dev1B commented on src/components/Comments/Comments.tsx
> +  if (commentsList && commentsList.length !== 0) {
commentsList && commentsList.length !== 0 => commentsList?.length better)

2021-08-13 09:52 UTC, dev1B commented on src/utils/scrollToElement.tsx
> +function scrollToElement(className: string): void {
scrollToElement => scrollTo

2021-08-13 09:52 UTC, dev1B commented on src/types/blogTypes.tsx
> +export interface comment {
comment => Comment

2021-08-13 09:52 UTC, dev1B commented on src/types/blogTypes.tsx
> +  children: [];
?

2021-08-13 09:52 UTC, dev1B commented on src/types/blogTypes.tsx
> +export interface BlogState {
weird

2021-08-13 09:52 UTC, dev1B commented on src/pages/SignIn/SignIn.tsx
> +import FormErrorMessage from '../../components/FormErrorMessage/FormErrorMassage';
Massage ?

2021-08-13 09:52 UTC, dev1B commented on src/pages/BlogPost/BlogPostContainer.tsx
> +function mapDispatchToProps(dispatch: typeof store.dispatch) {
const actions = {
  addComment: BlogActions.addComment,
  };

2021-08-13 10:36 UTC, olehrdk commented on src/reducers/blog.tsx
> +            userName: `Anonim ${comments.length + 1}`,
nope, no-plusplus eslint rule

2021-09-02 20:31 UTC, dev1B requested changes

2021-09-02 20:31 UTC, dev1B commented on src/components/AddCommentForm/AddCommentForm.tsx
> +  if (textAreaValue && textAreaValue.length !== 0) disabled = false;
textAreaValue && textAreaValue.length => textAreaValue?.length

2021-09-02 20:31 UTC, dev1B commented on src/components/AddCommentForm/AddCommentForm.tsx
> +  let disabled: boolean = true;
https://react-hook-form.com/api/useformstate#useFormRef

2021-09-21 07:30 UTC, dev1B commented
Need to complete and reopen. No updates for a long time

2021-09-21 07:30 UTC, closed without merging