typ0
devneu/frontend pull request #35
Opened 2021-08-18 18:17 UTC by AntonSydorovych

## Ticket
Link to ticket:  https://bsalo.atlassian.net/browse/DEV-29

## Description
*Please provide a small summary of your changes and how they resolved the issues in the ticket:*

- Change 1
- Change 2

## Screenshots

(prefer animated gif)

## Checklist

- [x] Did you test it?
- [ ] Did you add tests?
- [ ] Did you add to the storybook?

2021-08-25 09:08 UTC, AntonSydorovych commented
fix facebook button

2021-08-25 09:12 UTC, AntonSydorovych commented
fix facebook button

2021-08-25 15:44 UTC, dev1B commented on src/pages/ForgotPassword/ForgotPassword.tsx
> +                  className="_reset-password"
_

2021-08-25 15:44 UTC, dev1B commented on src/pages/ForgotPassword/ForgotPassword.scss
> +        &._reset-password {
_

2021-08-25 15:45 UTC, dev1B commented on src/pages/ForgotPassword/ForgotPassword.tsx
> +              <Title className="title-form" level={2}>
antd -> title + paragraph

2021-08-25 15:46 UTC, dev1B commented on src/pages/ForgotPassword/ForgotPassword.tsx
> +              <Title className="title-form" level={2}>
https://ant.design/components/typography/#components-typography-demo-title

2021-08-30 10:40 UTC, dev1B requested changes

2021-08-30 10:40 UTC, dev1B commented on src/stories/ForgotPassword.stories.tsx
> +  title: 'Reset Password/ForgotPassword',
Pages/Forgot....

2021-08-30 10:40 UTC, dev1B commented on src/stories/ForgotPassword.stories.tsx
> +  argTypes: { backgroundColor: { control: 'color' } },
безтолкове 
`argTypes: { backgroundColor: { control: 'color' } },`

2021-08-30 10:40 UTC, dev1B commented on src/pages/ForgotPassword/ForgotPassword.tsx
> +              <div className="footer">
Може бути nav

2021-09-01 06:21 UTC, dev1B commented
@AntonSydorovych fix merge conflict to move forward

2021-09-01 06:32 UTC, dev1B approved these changes

2021-09-06 11:28 UTC, merged