DEV-57: start work with my branch
devneu/frontend pull request #39
Opened 2021-08-29 17:00 UTC by yefimchuk

## Ticket
Link to ticket:
https://bsalo.atlassian.net/browse/DEV-57?atlOrigin=eyJpIjoiYTA0YmE5NjY2NmM4NDhjNWI2ZGJlN2MxN2I5ODczYTAiLCJwIjoiaiJ9

## Description
*Please provide a small summary of your changes and how they resolved the issues in the ticket:*

- Create main chat component
## Screenshoot

![image](https://user-images.githubusercontent.com/88689773/131258714-30edbf16-170f-4cc0-9b89-ad7ac8da97b1.png)

## Checklist

- [] Did you test it?
- [] Did you add tests?
- [] Did you add to the storybook?

2021-08-31 19:37 UTC, Skitus commented on src/pages/Chat/Chat.scss
> +  display: flex;
pls don`t use flex and other styles we have antd

2021-08-31 19:37 UTC, Skitus commented on src/pages/Chat/Chat.scss
> +  display: flex;
pls check antd layout and fix it

2021-08-31 19:37 UTC, Skitus commented on src/pages/Chat/Chat.tsx
>  import './Chat.scss';
pls push it import to he ends of the imports

2021-08-31 19:37 UTC, Skitus commented on src/pages/Chat/Chat.tsx
> +    <div className="main">
dont use your own styles and layouts pls use antd

2021-08-31 19:37 UTC, Skitus commented on src/pages/Chat/Chat.tsx
> +    <div className="main">
fix all this file

2021-08-31 19:37 UTC, Skitus commented on src/pages/Chat/Chat.tsx
>  import './Chat.scss';
import './Chat.scss';

2021-09-21 07:31 UTC, dev1B requested changes

2021-09-21 07:32 UTC, dev1B commented
Need to complete and reopen. No updates for a long time

2021-09-21 07:32 UTC, closed without merging