added side widget
devneu/frontend pull request #40
Opened 2021-08-30 15:56 UTC by AntonSydorovych

## Ticket
Link to ticket: https://bsalo.atlassian.net/browse/DEV-53

## Description
Added a Side Widget component

- Side Widget component was copied from Search component and changed;
- Change 2

![image](https://user-images.githubusercontent.com/45861810/131367441-7f9a4676-8ea6-47d0-97eb-270b563969a1.png)

(prefer animated gif)

## Checklist

- [x] Did you test it?
- [x] Did you add tests?
- [x] Did you add to the storybook?

2021-08-31 19:26 UTC, Skitus commented on src/components/Side/Side.scss
> +.ant-form-inline {
pls don`t use classes of antd , use it with selectors (.side-widget-card .ant-form-inline )

2021-08-31 19:26 UTC, Skitus commented on src/components/Side/Side.tsx
> +      <Form onFinish={handleSubmit(onSubmit)} layout="inline">
Weird. You have to use text inside this card not Form

2021-08-31 19:26 UTC, Skitus commented on src/components/Side/Side.tsx
> +    <Card title="Side Widget" className="side-widget-card">
className="..." title="..."

2021-08-31 19:26 UTC, Skitus commented on src/components/Side/Side.tsx
> +  const onSubmit = (data: any) => console.log('Search result', data);
pls delete this

2021-08-31 19:26 UTC, Skitus commented on src/stories/Side.stories.tsx
> +  argTypes: { backgroundColor: { control: 'color' } },
delete this pls

2021-08-31 19:26 UTC, Skitus commented on src/stories/Side.stories.tsx
> +export const Primary = Template.bind({});
delete this

2021-08-31 19:26 UTC, Skitus commented on src/stories/Side.stories.tsx
> +Primary.args = { message: 'message' };
same

2021-08-31 19:27 UTC, Skitus commented on src/components/Side/Side.scss
> +.ant-form-inline {
add pls color to your header

2021-08-31 19:31 UTC, Skitus commented on src/components/Side/Side.scss
> +.ant-form-inline {
Maybe u don`t need this file

2021-09-01 06:37 UTC, dev1B requested changes

2021-09-01 06:37 UTC, dev1B commented on src/components/Side/Side.scss
> +.side-widget-card {
.side-widget достатньо)

2021-09-01 06:37 UTC, dev1B commented on src/components/Side/Side.scss
> +.ant-form-inline {
Ізоляція, перепишеш стилі сусіда)

2021-09-01 06:37 UTC, dev1B commented on src/components/Side/Side.test.tsx
> +import SideWidget from './Side';
import SideWidget from './Side';

Side => SideWidget

2021-09-01 06:37 UTC, dev1B commented on src/components/Side/Side.tsx
> +import './Side.scss';
src/components/Side/Side.tsx - finename

2021-09-01 06:37 UTC, dev1B commented on src/components/Side/Side.tsx
> +    <Card title="Side Widget" className="side-widget-card">
Краще спершу писати клас а потім все інше, спрощує читання коду)

2021-09-01 06:37 UTC, dev1B commented on src/pages/Blog/Blog.tsx
> +import SideWidget from '../../components/Side/Side';
import SideWidget from '../../components/Side/Side';

`/Side/Side';`

2021-09-01 06:37 UTC, dev1B commented on src/stories/Side.stories.tsx
> +  argTypes: { backgroundColor: { control: 'color' } },
@Skitus А ти не видаляєш)))

2021-09-01 06:37 UTC, dev1B commented on src/stories/Side.stories.tsx
> +Primary.args = { message: 'message' };
`const SideWidget = () => {`

твій компонент ніц не приймає)

2021-09-03 10:43 UTC, dev1B requested changes

2021-09-03 10:43 UTC, dev1B commented on src/components/SideWidget/SideWidget.tsx
> +  const text = `You can put anything you want inside
remove `const text`

2021-09-03 10:43 UTC, dev1B commented on src/stories/SideWidget.stories.tsx
> +  title: 'Widget/SideWidget',
Widget => Widgets ?

2021-09-03 17:04 UTC, merged