DEV-56 add static version
devneu/frontend pull request #42
Opened 2021-09-03 20:00 UTC by OlegDsalo

## Ticket
Link to ticket:
https://bsalo.atlassian.net/secure/RapidBoard.jspa?rapidView=3&modal=detail&selectedIssue=DEV-56
## Description
*Please provide a small summary of your changes and how they resolved the issues in the ticket:*

-add static version (unfinished group-members)
- Change 2

## Screenshots
![image](https://user-images.githubusercontent.com/87490184/132059533-c385ac5c-271e-4daa-8e20-d9179620f398.png)

(prefer animated gif)

## Checklist

- [ ] Did you test it?
- [ ] Did you add tests?
- [ ] Did you add to the storybook?

2021-09-05 16:21 UTC, dev1B requested changes

2021-09-13 06:26 UTC, dev1B requested changes

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatAttachments.tsx
> +    <Button className="show-all">View all</Button>
Де стилі для цього класу ?

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatGallery.tsx
> +        // eslint-disable-next-line react/no-array-index-key
?

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatGallery.tsx
> +const ChatGallery = ({ photos }: any) => (
interface?

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatAttachments.tsx
> +  <div className="attachments">
chat-attachments?

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatGroupMembers.tsx
> +import SimpleSlider from './SimpleSlider';
SimpleSlider ?

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatGroupMembers.tsx
> +const ChatGroupMembers = ({ data }: any) => (
any...

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatPreview.tsx
> +    <ChatAttachments attachments={fileImg} />
fileImg ?
galleryImg?
groupMembersImg??

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/ChatUserInfo.tsx
> +      <>
remove, key ?

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/SimpleSlider.tsx
> +const SimpleSlider = ({ slider }: any) => {
any

2021-09-13 06:26 UTC, dev1B commented on src/components/ChatPreview/SimpleSlider.tsx
> +          <div>
key?

2021-09-13 20:13 UTC, OlegDsalo commented on src/components/ChatPreview/ChatAttachments.tsx
> +    <Button className="show-all">View all</Button>
В загальному файлі( ChatPreview.scss) шоб не повторювати 2 рази

2021-09-21 07:18 UTC, dev1B requested changes

2021-09-21 07:18 UTC, dev1B commented on src/components/ChatGallery/ChatGallery.tsx
> +interface photosProps {
photosProps => ChatGalleryProps

2021-09-21 07:18 UTC, dev1B commented on src/components/ChatAttachments/ChatAttachments.tsx
> +const ChatAttachments = ({ attachments }: attachmentsProps) => (
ChatAttachmentsProps

2021-09-21 07:18 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +interface SliderProps {
SliderProps?

2021-09-21 07:18 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +    className: 'simpleSlider',
simpleSlider?

2021-09-21 07:18 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +  slider: ChatData[];
slides? items?

2021-09-21 07:18 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +    <div className="simple-slider">
className: 'simpleSlider', 
one more times?)

2021-09-21 07:18 UTC, dev1B commented on src/components/ChatUserInfo/ChatUserInfo.tsx
> +interface UserInfoProps {
?

2021-09-21 07:18 UTC, dev1B commented on src/mock/mockChat.ts
> +  memberImg: [
memberImg ? just one image?


image = 1 
images = 2+

2021-09-21 07:18 UTC, dev1B commented on src/types/ChatPreview.interface.tsx
> +export interface ChatData {
Дивний інтерфейс, тому що ти його юзаєш всюди(

2021-09-21 07:21 UTC, dev1B commented
Проглянь скріншоти і постарайся зробити наближене, ти опустив багато деталей)

2021-09-23 11:33 UTC, dev1B requested changes

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatAttachments/ChatAttachments.tsx
> +      {attachments.map((attachment: any) => (
attachment: any? 
Видали `any`, воно не має матюкатися)

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatAttachments/ChatAttachments.tsx
> +      <strong>ATTACHMENTS</strong>
Attachments => use uppercase style for it

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatAttachments/ChatAttachments.tsx
> +    <Paragraph>
https://ant.design/components/typography/#Typography.Paragraph

![image](https://user-images.githubusercontent.com/15249473/134498893-ce7605d8-3eb6-406f-ac32-b43ae26f4abf.png)

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatAttachments/ChatAttachments.tsx
> +      <strong>ATTACHMENTS</strong>
strong? ^^

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGallery/ChatGallery.tsx
> +    <Paragraph>
the same

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGallery/ChatGallery.tsx
> +      {photos.map((photo: any) => (
any?

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatGroupMembers.tsx
> +  data: groupData;
groupData ???

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatGroupMembers.tsx
> +        <div className="main-user-name">
Для чого тобі стронг тут ?

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +  slides: groupData[];
groupData?

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +  const oneSlidePhotos = 6;
const ITEMS_PER_SLIDE = 6;

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +  const lastSlide = Math.ceil(amountOfPhotos / oneSlidePhotos);
lastSlideNumber could be better

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +  const SliderArrowPrev = ({ currentSlide, slideCount, ...props }: any) => (
any)

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +      setActiveSlide(next + 1);
Для чого це ?

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +        {slides.map((item: any) => (
any

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +        <p>
Для чого тобі тут `p`? ніби лишній елемент

2021-09-23 11:33 UTC, dev1B commented on src/components/ChatPreview/ChatPreview.tsx
> +  const isGroup: boolean = true;
для чого це ?)

2021-09-23 11:33 UTC, dev1B commented on src/types/ChatPreview.interface.tsx
> +export interface groupData {
groupData => GroupData

Слово `data' дуже абстратне. Може просто GroupChat, або просто Chat

chats: Chat[]

2021-09-23 20:07 UTC, dev1B requested changes

2021-09-23 20:07 UTC, dev1B commented on src/components/ChatGroupMembers/ChatSlider.tsx
> +    <div className="chat-slider">
Для чого цей врапер ?

2021-09-27 06:53 UTC, dev1B requested changes

2021-09-27 07:12 UTC, dev1B requested changes

2021-09-27 07:12 UTC, dev1B commented on src/components/ChatSlider/ChatSlider.tsx
> +  const SliderArrowNext = ({ currentSlide, slideCount, ...props }: CustomArrowProps) => (
Для чого `currentSlide, slideCount, ...props` це тут ?

2021-09-27 17:09 UTC, dev1B approved these changes

2021-09-27 20:15 UTC, merged